# File for specifying Prayers in Rosarium
#
# Each page, seperated by '---' represents one tab of Rosarium
# Each page has a title, specifying the to-be-localized title of the window
# A list of prayer groups is specified
# which lists groups of prayers at single depth
# Finally, an order is specified
# It lists prayers in the order they should be prayed
# Groups can be used instead of filenames

title: "evening_prayer"
prayers:
  closing:
    - "st_antiochus"
    - "st_marcarius_the_great"
    - "oratio_Iesu"
order:
  - "te_lucis_ante_terminum"
  - "prayer_before_sleep"
  - "troparia_before_sleep"
  - closing:
      count: 1 # TODO: Count ranges like 0-4
      random: true
---
---
---
